import academyIcon from "../assets/AcademyIcon.svg";
import star from "../assets/star.svg";
import locationIcon from "../assets/location.svg";
import groupIcon from "../assets/UsersFour.svg";
import tierIcom from "../assets/TreeStructure.svg";
import hyderabadFc from "../assets/HyderabadFx.svg";
import sreenidhi from "../assets/image81.svg";
import abbas from "../assets/image 82.svg";
import onslaught from "../assets/image 83.svg";
import telanganafc from "../assets/image 84.svg";
import southcentral from "../assets/image 86.svg";
import ywa from "../assets/image 87.svg";
import benguluru from "../assets/image 88.png";
import mumbai from "../assets/image 89.png";
import chennai from "../assets/image 90.png";
import kerala from "../assets/image 91.png"
import eastBengal from "../assets/image 92.png";
import secunderabad from "../assets/image 80.png"
export const detailedCardList = [
  {
    id: 1,
    academyIcon: academyIcon,
    certification: "AIFF Certified",
    clubImage: hyderabadFc,
    star: star,
    years: "10 years",
    title: "Hyderabad FC",
    description:
      "Founded in 2019, Hyderabad FC competes in the Indian Super League (ISL) and represents the city of Hyderabad at the national level.",
    locationIcon: locationIcon,
    location: "Gachibowli",
    groupIcon: groupIcon,
    group: "State Level",
    tierIcon: tierIcom,
    tier: "Tier 2",
    tierFlag: true,
  },
  {
    id: 2,
    academyIcon: academyIcon,
    certification: "AIFF Certified",
    clubImage: sreenidhi,
    star: star,
    years: "09 years ",
    title: "Sreenidi Deccan Football Club",
    description:
      "SDFC was founded on 1st January 2015 becoming a professional Football Club in May 2018, got its first accreditation with AIFF",
    locationIcon: locationIcon,
    location: "Kondapur",
    groupIcon: groupIcon,
    group: "State Level",
    tierIcon: tierIcom,
    tier: "Tier 2",
    tierFlag: true,
  },
  {
    id: 3,
    academyIcon: academyIcon,
    certification: "AIFF Certified",
    clubImage: abbas,
    star: star,
    years: "09 years ",
    title: "Abbas union Football club",
    description:
      'Abbas Union Football Club participates in "A" Division Raheem League Football Tournament organized by Telangana Football Association.',
    locationIcon: locationIcon,
    location: "Nampally",
    groupIcon: groupIcon,
    group: "State Level",
    tierIcon: tierIcom,
    tier: "Tier 2",
    tierFlag: false,
  },
  {
    id: 4,
    academyIcon: academyIcon,
    certification: "AIFF Certified",
    clubImage: onslaught,
    star: star,
    years: "09 years ",
    title: "Onslaught Football Academy",
    description:
      "Onslaught Football Academy in Madhapur, Hyderabad is a top player in the category Football Coaching Classes in the Hyderabad. ",
    locationIcon: locationIcon,
    location: "Gandipet",
    groupIcon: groupIcon,
    group: "State Level",
    tierIcon: tierIcom,
    tier: "Tier 3",
    tierFlag: true,
  },
  {
    id: 5,
    academyIcon: academyIcon,
    certification: "AIFF Certified",
    clubImage: telanganafc,
    star: star,
    years: "10 years ",
    title: "Telangana Police FC",
    description:
      "The football team associated with the Telangana State Police Department, participating in various local & state-level tournaments.",
    locationIcon: locationIcon,
    location: "Hyderabad",
    groupIcon: groupIcon,
    group: "State Level",
    tierIcon: tierIcom,
    tier: "Tier 2",
    tierFlag: true,
  },

  {
    id: 6,
    academyIcon: academyIcon,
    certification: "AIFF Certified",
    clubImage: southcentral,
    star: star,
    years: "09 years ",
    title: "South Central Railway FC",
    description:
      "The football club of the South Central Railway, which competes in local leagues and tournaments in Hyderabad.",
    locationIcon: locationIcon,
    location: "Hyderabad",
    groupIcon: groupIcon,
    group: "State Level",
    tierIcon: tierIcom,
    tier: "Tier 2",
    tierFlag: true,
  },
  {
    id: 7,
    academyIcon: academyIcon,
    certification: "AIFF Certified",
    clubImage: ywa,
    star: star,
    years: "09 years ",
    title: "YWA Football Club",
    description:
      'Abbas Union Football Club participates in "A" Division Raheem League Football Tournament organized by Telangana Football Association.',
    locationIcon: locationIcon,
    location: "Uppal",
    groupIcon: groupIcon,
    group: "Local Level",
    tierIcon: tierIcom,
    tier: "Tier 2",
    tierFlag: false,
  },
  {
    id: 8,
    academyIcon: academyIcon,
    certification: "AIFF Certified",
    clubImage: onslaught,
    star: star,
    years: "09 years ",
    title: "Onslaught Football Academy",
    description:
      "Onslaught Football Academy in Madhapur, Hyderabad is a top player in the category Football Coaching Classes in the Hyderabad. ",
    locationIcon: locationIcon,
    location: "Gandipet",
    groupIcon: groupIcon,
    group: "State Level",
    tierIcon: tierIcom,
    tier: "Tier 3",
    tierFlag: true,
  },
  {
    id: 9,
    academyIcon: academyIcon,
    certification: "AIFF Certified",
    clubImage: benguluru,
    star: star,
    years: "09 years ",
    title: "Bengaluru FC",
    description:
      "Bengaluru FC, founded in 2013. They have won several titles, including then Hyderabad.",
    locationIcon: locationIcon,
    location: "Bengaluru",
    groupIcon: groupIcon,
    group: "National Level",
    tierIcon: tierIcom,
    tier: "Tier 1",
    tierFlag: true,
  },
  {
    id: 10,
    academyIcon: academyIcon,
    certification: "AIFF Certified",
    clubImage: mumbai,
    star: star,
    years: "09 years ",
    title: "Mumbai City FC",
    description:
      "Mumbai City FC is a professional football club based in Mumbai, Maharashtra. Founded in 2014, the club competes in the Indian Super League (ISL)",
    locationIcon: locationIcon,
    location: "Mumbai",
    groupIcon: groupIcon,
    group: "National Level",
    tierIcon: tierIcom,
    tier: "Tier 1",
    tierFlag: true,
  },
  {
    id: 11,
    academyIcon: academyIcon,
    certification: "AIFF Certified",
    clubImage: chennai,
    star: star,
    years: "09 years ",
    title: "Chennaiyin FC",
    description:
      "Chennaiyin FC is a Chennai-based football club that competes in the Indian Super League (ISL). Established in 2014",
    locationIcon: locationIcon,
    location: "Chennai",
    groupIcon: groupIcon,
    group: "National Level",
    tierIcon: tierIcom,
    tier: "Tier 1",
    tierFlag: true,
  },
  {
    id: 12,
    academyIcon: academyIcon,
    certification: "AIFF Certified",
    clubImage: kerala,
    star: star,
    years: "09 years ",
    title: "Kerala Blasters FC",
    description:
      "Kerala Blasters FC is one of the most popular football clubs in India, based in Kochi, Kerala. Established in 2014",
    locationIcon: locationIcon,
    location: "Kochi",
    groupIcon: groupIcon,
    group: "National Level",
    tierIcon: tierIcom,
    tier: "Tier 1",
    tierFlag: true,
  },
  {
    id: 13,
    academyIcon: academyIcon,
    certification: "AIFF Certified",
    clubImage: eastBengal,
    star: star,
    years: "10 years ",
    title: "East Bengal FC",
    description:
      "East Bengal FC, founded in 1920, is one of the oldest and most storied football clubs in India. Based in Kolkata, West Bengal",
    locationIcon: locationIcon,
    location: "Kolkata",
    groupIcon: groupIcon,
    group: "National Level",
    tierIcon: tierIcom,
    tier: "Tier 1",
    tierFlag: true,
  },
  {
    id: 14,
    academyIcon: academyIcon,
    certification: "AIFF Certified",
    clubImage: secunderabad,
    star: star,
    years: "146 years ",
    title: "Secunderabad Club",
    description:
      "East Bengal FC, founded in 1920, is one of the oldest and most storied football clubs in India. Based in Kolkata, West Bengal",
    locationIcon: locationIcon,
    location: "Secunderabad",
    groupIcon: groupIcon,
    group: "State Level",
    tierIcon: tierIcom,
    tier: "Tier 3",
    tierFlag: true,
  },
  {
    id: 15,
    academyIcon: academyIcon,
    certification: "AIFF Certified",
    clubImage: hyderabadFc,
    star: star,
    years: "10 years",
    title: "Hyderabad FC",
    description:
      "Founded in 2019, Hyderabad FC competes in the Indian Super League (ISL) and represents the city of Hyderabad at the national level.",
    locationIcon: locationIcon,
    location: "Gachibowli",
    groupIcon: groupIcon,
    group: "State Level",
    tierIcon: tierIcom,
    tier: "Tier 2",
    tierFlag: true,
  },
  {
    id: 16,
    academyIcon: academyIcon,
    certification: "AIFF Certified",
    clubImage: southcentral,
    star: star,
    years: "09 years ",
    title: "South Central Railway FC",
    description:
      "The football club of the South Central Railway, which competes in local leagues and tournaments in Hyderabad.",
    locationIcon: locationIcon,
    location: "Hyderabad",
    groupIcon: groupIcon,
    group: "State Level",
    tierIcon: tierIcom,
    tier: "Tier 2",
    tierFlag: true,
  },
];
